export const ActionTypes = {
	SET_PRODUCTS: "SET_PRODUCTS",
	SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
	REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
	REMOVE_FROM_CART: "REMOVE_FROM_CART",
	ADD_TO_CART: "ADD_TO_CART",
	LOW_TO_HIGH: "LOW_TO_HIGH",
	HIGH_TO_LOW: "HIGH_TO_LOW",
	SEARCH_ITEMS: "SEARCH_ITEMS",
};
